// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDf-W8HqXeUeeFDJACQ_qjn6mqyL4CDkDA',
    appId: '1:929812100990:web:14fe5e73b10068b8dbe52f',
    messagingSenderId: '929812100990',
    projectId: 'alwaleed-education-platform',
    authDomain: 'alwaleed-education-platform.firebaseapp.com',
    storageBucket: 'alwaleed-education-platform.firebasestorage.app',
    measurementId: 'G-93T0GBC3KD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7yeiSp3Mf76AA3XqdtV14HycPasozbvY',
    appId: '1:929812100990:android:bbdc54931355cf1adbe52f',
    messagingSenderId: '929812100990',
    projectId: 'alwaleed-education-platform',
    storageBucket: 'alwaleed-education-platform.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBALMA4Q6QOHXXZDPvrPeJl5-F5NJLD5nc',
    appId: '1:929812100990:ios:c117d7436cb6e44edbe52f',
    messagingSenderId: '929812100990',
    projectId: 'alwaleed-education-platform',
    storageBucket: 'alwaleed-education-platform.firebasestorage.app',
    iosBundleId: 'com.example.alWaleed',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBALMA4Q6QOHXXZDPvrPeJl5-F5NJLD5nc',
    appId: '1:929812100990:ios:c117d7436cb6e44edbe52f',
    messagingSenderId: '929812100990',
    projectId: 'alwaleed-education-platform',
    storageBucket: 'alwaleed-education-platform.firebasestorage.app',
    iosBundleId: 'com.example.alWaleed',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDf-W8HqXeUeeFDJACQ_qjn6mqyL4CDkDA',
    appId: '1:929812100990:web:4663694aabe8dad2dbe52f',
    messagingSenderId: '929812100990',
    projectId: 'alwaleed-education-platform',
    authDomain: 'alwaleed-education-platform.firebaseapp.com',
    storageBucket: 'alwaleed-education-platform.firebasestorage.app',
    measurementId: 'G-DVH2JYCCDZ',
  );
}
